### ISSUE TITLE
How can i use this to create multi-user （multiple dash-clients ）in mininet ？

### ISSUE THREAD

**Issue by sjksong** [SoonyangZhang/http-dash-simu#1]

**Comment by SoonyangZhang** [comment]
https://github.com/SoonyangZhang/http-dash-simu/blob/main/dash/dash_client_test.cc#L79
```
std::vector<basic::DashClient*> clients;
for(int i=0;i<2;i++){
    std::string trace=std::to_string(i+1)+"_"+result;
    auto client=new basic::DashClient(epoll_server,duration,video_log,trace);
    client->SetAdaptationAlgorithm(adapation);
    bool success=client->AsynConnect(src_addr,dst_addr); 
    if(success){
        clients.push_back(client);
    }else{
        delete client;
    }
    
}
int n=clients.size();
while(g_running){
    epoll_server->WaitForEventsAndExecuteCallbacks();
    int count=0;
    for(auto it=clients.begin();it!=clients.end();it++){
        basic::DashClient* client=(*it);
        if(client->IsTerminated()){
            count++;
        }
    }
    if(count==n){
        break;
    }
}
while(!clients.empty()){
    auto it=clients.begin();
    basic::DashClient* client=(*it);
    clients.erase(it);
    delete client;
}
```

**Comment by sjksong** [comment]
i modified the 2h1s.py in the build folder , does it work in principle?
def send_receive_thread(client_p, possion_p):
    while True:
        ret = subprocess.Popen.poll(client_p)
        if ret is None:
            continue
        else:
            break
    os.killpg(os.getpgid(possion_p.pid), signal.SIGTERM)


def test_adaptation_algorithm(algo):
    net = Mininet(cleanup=True)

    c0 = net.addController(name='c0')

    s1 = net.addSwitch('s1')

    h1 = net.addHost('h1', ip='10.0.0.1')
    h2 = net.addHost('h2', ip='10.0.0.2')
    h3 = net.addHost('h3', ip='10.0.0.3')
    h4 = net.addHost('h4', ip='10.0.0.4')

    s1h4 = {'bw': 10, 'delay': '10ms'}
    net.addLink(s1, h4, cls=TCLink, **s1h4)
    h1s1 = {'bw': 4, 'delay': '10ms'}
    net.addLink(h1, s1, cls=TCLink, **h1s1)
    h2s1 = {'bw': 4, 'delay': '10ms'}
    net.addLink(h2, s1, cls=TCLink, **h2s1)
    h3s1 = {'bw': 4, 'delay': '10ms'}
    net.addLink(h3, s1, cls=TCLink, **h3s1)

    net.build()
    net.start()
    time.sleep(1)

    server_p = h4.popen("./t_dash_server -h 10.0.0.4 -p 3333")
    cmd = "./t_dash_client -r 10.0.0.4  -p 3333 -a  %s" % algo
    client_p1 = h1.popen(cmd)
    possion_p1 = h4.popen("./possion_sender 10.0.0.1 1234")

    client_p3 = h3.popen(cmd)
    possion_p3 = h4.popen("./possion_sender 10.0.0.3 1234")
    client_p2 = h2.popen(cmd)
    possion_p2 = h4.popen("./possion_sender 10.0.0.2 1234")
    t1=threading.Thread(target=send_receive_thread(client_p1,possion_p1))
    t2=threading.Thread(target=send_receive_thread(client_p2,possion_p2))
    t3=threading.Thread(target=send_receive_thread(client_p3,possion_p3))
    t1.start()
    t2.start()
    t3.start()

    os.killpg(os.getpgid(server_p.pid), signal.SIGTERM)
    server_p.wait()
    possion_p1.wait()
    possion_p2.wait()
    possion_p3.wait()
    net.stop()

**Comment by SoonyangZhang** [comment]
Yeah, got it. The method to create mulitple dash clients seems also ok.

**Comment by sjksong** [comment]
> Yeah, got it. The method to create mulitple dash clients seems also ok.

Thanks for your reply!!!

**Comment by SoonyangZhang** [comment]
Hope this helps.
```
#!/usr/bin/python
import time
import sys
import os
import threading
import subprocess
import signal

from mininet.cli import CLI
from mininet.log import lg, info
from mininet.node import Node
from mininet.util import quietRun
from mininet.net import Mininet
from mininet.link import TCLink
from mininet.link import Intf  
from mininet.node import OVSSwitch,Node

def test_adaptation_algorithm(algo):
    bottleneckbw=3
    nonbottlebw=500;
    rtt=40*3/2
    buffer_size =bottleneckbw*1000*rtt/(1500*8) 
    net = Mininet( cleanup=True )
    h1 = net.addHost('h1',ip='10.0.0.1')
    h2 = net.addHost('h2',ip='10.0.0.2')
    s1 = net.addSwitch( 's1' )
    c0 = net.addController('c0')
    net.addLink(h1,s1,intfName1='h1-eth0',intfName2='s1-eth0',cls=TCLink , bw=nonbottlebw, delay='10ms', max_queue_size=10*buffer_size)
    net.addLink(s1,h2,intfName1='s1-eth1',intfName2='h2-eth0',cls=TCLink , bw=bottleneckbw, delay='10ms', max_queue_size=buffer_size)    
    net.build()
    net.start()
    time.sleep(1)
    server_p=h2.popen("./t_dash_server -h 10.0.0.2 -p 3333")
    possion_p=h2.popen("./possion_sender 10.0.0.1 1234")
    cmd="./t_dash_client -r 10.0.0.2  -p 3333 -a  %s"%algo
    n=5
    clients=[]
    for i in range(n):
        client_p=h1.popen(cmd);
        clients.append(client_p)
    while True:
        total=len(clients)
        alive=total
        for i in range(total):
            ret=subprocess.Popen.poll(clients[i])
            if ret is None:
                continue
            else:
                alive-=1
        if alive==0:
            break
    os.killpg(os.getpgid(server_p.pid),signal.SIGTERM)
    os.killpg(os.getpgid(possion_p.pid),signal.SIGTERM)
    server_p.wait()  
    possion_p.wait()
    net.stop()
if __name__ == '__main__':
    algorithms=["festive","panda","tobasco","osmp","raahs","fdash","sftm","svaa"]
    for i in range(len(algorithms)):
        test_adaptation_algorithm(algorithms[i])
        print("done: "+algorithms[i])
```
